ministryofjustice/opg-sirius-lpa-frontend

- internal/sirius/create_task_test.go
Otherwise you get a 422 error
#patch
> Use future due date for task creation test

- internal/server/link_person.go
- internal/server/link_person_test.go
- internal/server/server.go
- internal/sirius/date_string.go
- internal/sirius/date_string_test.go
- internal/sirius/link_people.go
- internal/sirius/link_people_test.go
- internal/sirius/person.go
- internal/sirius/person_by_uid.go
- internal/sirius/person_by_uid_test.go
- web/template/link_person.gohtml
Users search for the UID of the person they want to link, check the details, select a primary record (if possible) and save.
Fixes VEGA-1251 #minor
> Add form to link two person records

- cypress/integration/change-status.spec.js
- internal/server/change_status.go
- internal/server/change_status_test.go
- internal/server/server.go
- internal/sirius/available_statuses.go
- internal/sirius/available_statuses_test.go
- internal/sirius/case.go
- internal/sirius/edit_case.go
- internal/sirius/edit_case_test.go
- web/template/change_status.gohtml
> Add form to change a case's status

- cypress/integration/unlink-person.spec.js
- internal/server/server.go
- internal/server/unlink_person.go
- internal/server/unlink_person_test.go
- internal/sirius/case.go
- internal/sirius/person.go
- internal/sirius/person_test.go
- internal/sirius/unlink_person.go
- internal/sirius/unlink_person_test.go
- web/assets/dark.scss
- web/assets/main.scss
- web/template/unlink_person.gohtml
Created form & updated dark mode scss to style the table correctly. Added tests
> Recreate unlink record form

- cypress/integration/unlink-person.spec.js
- internal/sirius/unlink_person_test.go
They're causing problems in the prod build
> Temporarily remove unlink person tests

- cypress/integration/create-relationship.spec.js
- internal/sirius/person.go
And extend Create relationship to cover the uid to stop this happening again
#patch
> Fix case of `uId` property in response

- cypress/integration/unlink-person.spec.js
- internal/sirius/person_test.go
- internal/sirius/unlink_person.go
- internal/sirius/unlink_person_test.go
Uncommented unlink person pact test. 
Issue not discovered yet, will see if failure on build pipeline provides more insight
VEGA-1252 #patch
> VEGA-1252 Fix unlink person pact tests

- .github/workflows/build.yml
- cypress/e2e/create-donor.cy.js
- go.mod
- go.sum
- internal/server/create_donor.go
- internal/server/create_donor_test.go
- internal/server/server.go
- internal/sirius/create_donor.go
- internal/sirius/create_donor_test.go
- internal/sirius/person.go
- sonar-project.properties
- web/template/donor.gohtml
> Add form for creating a donor

- web/template/donor.gohtml
It got caught up as a text input
For VEGA-1240 #patch
> Return DOB to date input

- cypress/e2e/edit-donor.cy.js
- internal/server/create_donor.go
- internal/server/edit_donor.go
- internal/server/edit_donor_test.go
- internal/server/server.go
- internal/sirius/edit_donor.go
- internal/sirius/edit_donor_test.go
- web/template/donor.gohtml
Reuse the template from "Create Donor", with some slight modifications for messages.
For VEGA-1244 #minor
> Add "Edit Donor" form

- web/template/change_status.gohtml
So that users can't set an empty status
For VEGA-1423 #patch
> Make status dropdown required

- cypress/e2e/edit-payment.cy.js
- internal/server/add_payment.go
- internal/server/edit_payment.go
- internal/server/edit_payment_test.go
- internal/server/server.go
- internal/sirius/edit_payment.go
- internal/sirius/edit_payment_test.go
- internal/sirius/payment.go
- internal/sirius/payment_test.go
- web/template/add_payment.gohtml
- web/template/edit_payment.gohtml
- web/template/payments.gohtml
Version 1 of the edit payments widget
VEGA-1393 #minor
> VEGA 1393 edit payment widget

- web/assets/dark.scss
- web/template/payments.gohtml
prefixed add and edit payment link so that they are correct when embedded in sirius
> VEGA-1393 prefix add and edit payment links correctly

- web/assets/select.js
When using an autocomplete: if a fetch request is already in motion when a new one is issued, then abort it.
This will prevent race conditions where earlier requests land after newer ones.
Fixes VEGA-1474 #patch
> Abort overlapping fetch requests

- cypress/e2e/edit-payment.cy.js
- internal/sirius/ref_data_test.go
added new payment source ref data
> Fix failing pact test due to ref data

- internal/server/get_payments.go
- internal/server/get_payments_test.go
- internal/sirius/payment.go
- internal/sirius/ref_data.go
- web/template/payments.gohtml
> Show references in payment details

- cypress/e2e/delete-fee-reduction.cy.js
- internal/server/delete_payment.go
- internal/server/delete_payment_test.go
- internal/server/server.go
- internal/sirius/delete_payment_test.go
- internal/sirius/payment_test.go
- main.go
- web/template/delete_fee_reduction.gohtml
Users can delete a saved fee reduction, also adds `translateRefData` and `ToLower` template functions for formatting content
#minor
> VEGA-1464 delete a saved fee reduction

- .github/workflows/build.yml
- web/assets/dark.scss
> Support dark mode in notification banner component

- cypress/e2e/create-investigation.cy.js
- internal/server/create_investigation.go
- internal/server/create_investigation_test.go
- internal/server/server.go
- internal/sirius/create_investigation.go
- internal/sirius/create_investigation_test.go
- internal/sirius/investigation.go
- web/template/create_investigation.gohtml
- web/template/investigation.gohtml
> VEGA-1441 Recreate investigation form

- cypress/e2e/take-investigation-off-hold.cy.js
- internal/server/server.go
- internal/server/take_investigation_off_hold.go
- internal/server/take_investigation_off_hold_test.go
- internal/sirius/hold_period.go
- internal/sirius/hold_period_test.go
- internal/sirius/take_investigation_off_hold.go
- internal/sirius/take_investigation_off_hold_test.go
- web/template/investigation_off_hold.gohtml
- web/template/investigation_on_hold.gohtml
Recreated the take investigation off hold form
VEGA-1532 #minor
> VEGA-1532 recreate take investigation off hold form

- internal/server/add_payment.go
- internal/server/apply_fee_reduction.go
- internal/server/delete_payment.go
Remove the text "Please clear the task if you have completed it" since it may be confusing.
Fixes VEGA-1529 #minor
> Remove extra description from payment flash messages

- web/template/search.gohtml
> Link deputies to deputy hub, not client page

- .github/workflows/build.yml
- docker/sirius-lpa-frontend/Dockerfile
And set required default branch config for `anothrNick/github-tag-action`
#patch
> Bump insecure versions of libraries

- web/assets/main.scss
set `$moj-assets-path` in main.scss
> VEGA-1648 Icons not showing in search results page

- web/template/search.gohtml
Sorts surnames in lowercase format as the sort order is case sensitive
> VEGA-1649 convert surnames to lowercase when sorting

- cypress/e2e/add-complaint.cy.js
- cypress/e2e/edit-complaint.cy.js
- internal/server/add_complaint.go
- internal/server/add_complaint_test.go
- internal/server/edit_complaint.go
- internal/server/edit_complaint_test.go
- internal/sirius/add_complaint_test.go
- internal/sirius/complaint.go
- internal/sirius/edit_complaint_test.go
- internal/sirius/ref_data.go
- internal/sirius/ref_data_test.go
- web/template/add_complaint.gohtml
- web/template/edit_complaint.gohtml
Add ComplainantCategory and Origin
Fixes VEGA-1654 #minor
> Add new fields to Add/Resolve Complaint forms

- cypress/e2e/edit-complaint.cy.js
- internal/server/add_complaint.go
- internal/server/add_complaint_test.go
- internal/server/edit_complaint.go
- internal/server/edit_complaint_test.go
- internal/sirius/ref_data.go
- internal/sirius/ref_data_test.go
- web/template/add_complaint.gohtml
- web/template/edit_complaint.gohtml
Removes hardcoded complaint category/subcategory translations and instead makes a request to retrieve the refdata
> VEGA-1667 request complaints category refdata

- cypress/e2e/search.cy.js
- web/assets/dark.scss
- web/assets/main.scss
- web/template/layout/deleted_cases.gohtml
- web/template/layout/pagination.gohtml
- web/template/layout/search_filter.gohtml
- web/template/search.gohtml
> VEGA-1704 combined search result changes

- internal/server/edit_document.go
- internal/server/edit_document_test.go
- internal/sirius/document.go
- internal/sirius/document_test.go
Can now filter for doc types when retrieving documents by case so client side logic has been removed
> VEGA-1664 get draft documents via query param

- internal/server/create_document.go
- internal/server/create_document_test.go
Invalid inserts should appear above other inserts.
Fixes VEGA-1726 #minor
> Prioritise invalid inserts

- .github/pull_request_template.md
The checklist will act as a reminder for things that are commonly forgotten
VEGA-1768
> VEGA-1768 created PR template checklist

- internal/sirius/create_warning.go
- internal/sirius/create_warning_test.go
> VEGA-1835 use new warnings endpoint

- cypress/e2e/create-draft.cy.js
- internal/server/create_draft.go
- internal/server/create_draft_test.go
- internal/server/postcode_lookup.go
- internal/server/postcode_lookup_test.go
- internal/server/server.go
- internal/sirius/create_draft.go
- internal/sirius/create_draft_test.go
- internal/sirius/postcode_lookup.go
- internal/sirius/postcode_lookup_test.go
- internal/templatefn/fn.go
- web/assets/address-finder.js
- web/assets/main.scss
- web/template/create-draft.gohtml
- web/template/layout/input.gohtml
> Form to create draft LPA

- internal/server/create_draft.go
- internal/server/create_draft_test.go
- internal/server/server.go
- internal/sirius/get_user_details_test.go
To avoid people trying to make a request that we know won't succeed.
Fixes VEGA-1776 #patch
* N/A
* N/A
* N/A
> Check permissions for viewing digital LPAs page

- internal/server/create_document.go
- internal/server/create_document_test.go
- web/template/create_document.gohtml
Also rename the Success variable to make it clear what the success is, and remove unused reference to it.
> VEGA-1870 Remove <meta> element which causes page reload #patch

- docker/pact-stub/pact_stub.go
- internal/server/create_draft.go
- internal/server/create_draft_test.go
- internal/sirius/ref_data.go
- internal/sirius/ref_data_test.go
- web/assets/address-finder.js
- web/template/create-draft.gohtml
- web/template/layout/select.gohtml
Rather than country fields being a free text field, use a dropdown populated from the "country" ref data.
I also removed some duplication in the refdata tests: they're all test cases of the same basic operation so can be done in one test harness.
Fixes VEGA-1876 #minor
> Use dropdown for country selector

- cypress/e2e/digital-lpa.cy.js
- internal/server/create_draft.go
- internal/server/create_draft_test.go
- internal/server/lpa.go
- internal/server/lpa_test.go
- internal/server/server.go
- internal/sirius/date_string.go
- internal/sirius/date_string_test.go
- internal/sirius/digital_lpa.go
- internal/sirius/digital_lpa_test.go
- internal/templatefn/fn.go
- web/assets/dark.scss
- web/assets/main.scss
- web/template/create-draft.gohtml
- web/template/lpa.gohtml
Plus the API method to retrieve it, and making the link in the create draft flow work.
Fixes VEGA-1778 #minor
> Add route for viewing a draft LPA

- .github/pull_request_template.md
- .github/workflows/build.yml
- cypress/e2e/add-payment.cy.js
- cypress/e2e/apply-fee-reduction.cy.js
- cypress/e2e/create-document.cy.js
- cypress/e2e/create-investigation.cy.js
- cypress/e2e/delete-fee-reduction.cy.js
- cypress/e2e/delete-payment.cy.js
- cypress/e2e/edit-document.cy.js
- cypress/e2e/edit-investigation.cy.js
- cypress/e2e/edit-payment.cy.js
- cypress/e2e/edit_fee_reduction.cy.js
- cypress/e2e/mi-reporting.cy.js
- cypress/e2e/payments.cy.js
- cypress/e2e/place-investigation-on-hold.cy.js
- cypress/e2e/search.cy.js
- cypress/e2e/take-investigation-off-hold.cy.js
- package.json
- renovate.json
- web/assets/address-finder.js
- web/assets/auto-apply-filter.js
- web/assets/full-width-container.js
- web/assets/handle-create-document-button.js
- web/assets/search-controller.js
- web/assets/select.js
- web/assets/show-hide-filter.js
- web/assets/text-editor.js
- web/assets/todays-date.js
- web/assets/wysiwyg.scss
Prettier will now be run as part of the pipeline. I ran `yarn prettier` to fix existing issues
For VEGA-1885 #patch
> Add Prettier to pipeline and fix issues

- internal/sirius/digital_lpa.go
- internal/sirius/digital_lpa_test.go
- web/template/lpa.gohtml
> VEGA-1896 display digital lpa objection count

- web/template/lpa.gohtml
Application format is Digital for Digital LPA VEGA-1980 #minor
> Application format is Digital for Digital LPA VEGA-1980 #minor

- internal/server/get_payments.go
- internal/server/get_payments_test.go
- internal/server/mock_server.go
- internal/server/server.go
VEGA-1961 #patch
~~- [ ] I have updated the end-to-end tests to work with my changes~~
~~- [ ] I have added styling for Dark Mode~~
~~- [ ] I have checked that my UI changes meet accessibility standards~~
> VEGA-1961 remove old payments route

- web/template/warning.gohtml
EPA shown for EPA cases when creating a warning VEGA-1992 #minor
> VEGA-1992 EPA shown for EPA cases

- cypress/e2e/digital-lpa.cy.js
- cypress/mocks/migrated-from-pact.json
- internal/server/get_payments.go
- internal/server/get_payments_test.go
- internal/server/lpa_test.go
- internal/server/server.go
- internal/sirius/digital_lpa.go
- internal/sirius/digital_lpa_test.go
- internal/templatefn/fn.go
- web/assets/dark.scss
- web/assets/main.scss
- web/template/layout/mlpa-header.gohtml
- web/template/lpa.gohtml
- web/template/mlpa-payments.gohtml
> VEGA-1961 add fees tab to mlpa case page

- cypress/e2e/digital-lpa.cy.js
- cypress/mocks/common.json
- internal/server/get_documents.go
- internal/server/get_documents_test.go
- internal/server/server.go
- internal/templatefn/fn.go
- web/template/layout/mlpa-header.gohtml
- web/template/mlpa-documents.gohtml
VEGA-1990 #minor
~~- [ ] I have updated the end-to-end tests to work with my changes~~
~~- [ ] I have added styling for Dark Mode~~ No changes required
> VEGA-1990 MLPA documents tab

- cypress/e2e/add-payment.cy.js
- cypress/mocks/migrated-from-pact.json
- internal/server/add_payment.go
- internal/server/add_payment_test.go
- web/assets/main.scss
- web/template/mlpa-payments.gohtml
> VEGA-1982 Add payment to a modernised LPA

- internal/server/create_draft.go
- internal/server/create_draft_test.go
- internal/sirius/create_draft.go
- internal/sirius/create_draft_test.go
- web/template/create-draft.gohtml
> VEGA-2020 create donor and correspondent split name fields 

- internal/server/lpa.go
- internal/sirius/digital_lpa.go
Some leftovers from VEGA-1778
#patch
> Remove unnecessary logging

- internal/sirius/digital_lpa_test.go
> VEGA-2020 temporarily remove digital lpa pact test to switch name fields

- .github/workflows/codeql-analysis.yml
- cypress/e2e/edit-document.cy.js
- internal/server/edit_document.go
- internal/server/edit_document_test.go
- internal/sirius/document_templates.go
- internal/sirius/document_templates_test.go
- web/template/edit_document.gohtml
So that users understand the letter will be sent automatically rather than batched to Print & Post
Fixes VEGA-2038 #minor
> Show warning when publishing notify letters

- cypress/e2e/add-payment.cy.js
- cypress/e2e/apply-fee-reduction.cy.js
- cypress/mocks/migrated-from-pact.json
- internal/server/apply_fee_reduction.go
- internal/server/apply_fee_reduction_test.go
- web/template/mlpa-payments.gohtml
> VEGA-1983 Apply fee reduction to a digital LPA #minor

- cypress/e2e/add-fee-decision.cy.js
- cypress/mocks/common.json
- cypress/mocks/migrated-from-pact.json
- internal/server/add_fee_decision.go
- internal/server/add_fee_decision_test.go
- internal/server/add_payment.go
- internal/server/add_payment_test.go
- internal/server/apply_fee_reduction.go
- internal/server/apply_fee_reduction_test.go
- internal/server/manage_fees.go
- internal/server/manage_fees_test.go
- internal/server/server.go
- internal/sirius/add_fee_decision.go
- internal/sirius/add_fee_decision_test.go
- internal/sirius/ref_data.go
- web/template/add_fee_decision.gohtml
- web/template/add_payment.gohtml
- web/template/apply_fee_reduction.gohtml
- web/template/manage_fees.gohtml
- web/template/mlpa-payments.gohtml
> VEGA-2093 Add UI to add a reduced fee decision to an LPA #minor

- Makefile
- cypress/e2e/digital-lpa.cy.js
- cypress/mocks/migrated-from-pact.json
- internal/server/lpa.go
- internal/server/task.go
- internal/server/task_test.go
- internal/server/warning.go
- web/template/lpa.gohtml
> VEGA-2109 Redirect warnings and tasks

- internal/sirius/document.go
- internal/sirius/document_test.go
- web/template/mlpa-documents.gohtml
> VEGA-2155 Change IN label depending on whether document file is available #minor

- .pre-commit-config.yaml
- package.json
To automatically fix styling of JS and SCSS files
#patch
> Add Prettier to pre-commit hooks

- internal/server/assign_task.go
- internal/server/assign_task_test.go
- internal/server/task.go
- internal/server/task_test.go
- web/template/assign_task.gohtml
- web/template/task.gohtml
Add assign to me option when creating task VEGA-1878 #minor
> VEGA-1878 Give users the option to assign a task to themselves

- renovate.json
Reduce frequency of minor/patch updates VEGA-2167 #minor
> VEGA-2167 Reduce frequency of minor/patch updates in Renovate to weekly

- cypress/e2e/digital-lpa.cy.js
- web/template/layout/mlpa-case-summary.gohtml
> VEGA-2194 reassign tasks from case summary

- internal/server/edit_document.go
- internal/server/edit_document_test.go
> VEGA-2207 After saving digital LPA document, redirect #minor

- web/assets/text-editor.js
> VEGA-2235 fixed file path to access css file for tiny mce editor

- cypress/e2e/digital-lpa.cy.js
- cypress/mocks/migrated-from-pact.json
- internal/server/get_lpa_details.go
- internal/server/get_lpa_details_test.go
- internal/server/server.go
- internal/sirius/digital_lpa.go
- web/template/layout/mlpa-header.gohtml
- web/template/mlpa-details.gohtml
> VEGA-2241 display LPA store data on LPA details page

- Makefile
- README.md
- docker/docker-compose.dev.yml
- package.json
- web/assets/main.scss
> VEGA-2216 Fix loading of assets when in dev mode #minor

- cypress/e2e/create-warning.cy.js
- internal/server/task.go
- internal/server/task_test.go
- web/template/edit_document.gohtml
- web/template/task.gohtml
- web/template/warning.gohtml
VEGA-2245 #patch
~~- [ ] I have updated the end-to-end tests to work with my changes~~ N/A
~~- [ ] I have added styling for Dark Mode~~ N/A
~~- [ ] I have checked that my UI changes meet accessibility standards~~ N/A
> VEGA-2245 correct cancel links for tasks, warnings, and edit document 

- web/template/warning.gohtml
VEGA-2245 #patch
~~- [ ] I have added styling for Dark Mode~~
~~- [ ] I have checked that my UI changes meet accessibility standards~~
> VEGA-2245 fix e2e failing warning tests

- internal/server/assign_task.go
- internal/server/assign_task_test.go
- [] I have updated the end-to-end tests to work with my changes
> VEGA-2240 Redirect back to digital LPA page after reassigning task #minor

- cypress/e2e/create-document-digital-lpa.cy.js
- internal/server/create_document_digital_lpa.go
- internal/server/create_document_digital_lpa_test.go
- internal/sirius/digital_lpa.go
- web/template/mlpa-create_document.gohtml
VEGA-2089 #patch
~~- [ ] I have updated the end-to-end tests to work with my changes~~ N/A
~~- [ ] I have added styling for Dark Mode~~ N/A
~~- [ ] I have checked that my UI changes meet accessibility standards~~ N/A
> VEGA-2089 send follow up docs to donor rather than correspondent on digital LPAs

- internal/templatefn/fn.go
> VEGA-2232 updated status tag colours

- cypress/e2e/digital-lpa.cy.js
- cypress/mocks/migrated-from-pact.json
- docker/sirius-lpa-frontend/Dockerfile
- internal/sirius/case_summary.go
- internal/sirius/case_summary_test.go
- internal/sirius/task_test.go
- internal/sirius/warning.go
- internal/sirius/warning_test.go
- internal/templatefn/fn.go
- web/assets/main.scss
- web/template/layout/mlpa-case-summary.gohtml
> VEGA-2195 Show warnings in case summary #minor

- internal/sirius/digital_lpa.go
- internal/templatefn/fn.go
https://opgtransform.atlassian.net/browse/VEGA-2269
> VEGA-2269 Fix case tab headings

- web/template/layout/page.gohtml
These moved in govuk-frontend v5, but I msised them on the previous PR.
For VEGA-2202 #patch
> Fix paths to icons

- cypress/e2e/create-draft.cy.js
- cypress/e2e/digital-lpa.cy.js
- cypress/mocks/migrated-from-pact.json
- internal/server/create_draft_test.go
- internal/sirius/create_draft_test.go
- internal/sirius/digital_lpa_test.go
- internal/templatefn/fn.go
- web/template/create-draft.gohtml
- web/template/create_document.gohtml
- web/template/edit_document.gohtml
- web/template/layout/case-details.gohtml
- web/template/layout/mlpa-header.gohtml
- web/template/lpa.gohtml
- web/template/mlpa-documents.gohtml
- web/template/payments.gohtml
- web/template/search.gohtml
- web/template/warning.gohtml
> VEGA-2256 Switch to new digital LPA subtypes #minor

- cypress/e2e/search.cy.js
- web/template/search.gohtml
> VEGA-2309 Fix error on search page when person has no cases #minor

- go.mod
- go.sum
> SP-1961 - Update protobuff due to vuln #minor

- cypress/e2e/digital-lpa.cy.js
- internal/templatefn/fn.go
- web/template/mlpa-details.gohtml
[vega-2131](https://opgtransform.atlassian.net/browse/VEGA-2131)
> vega-2131 digital lpa accordions

- .github/CODEOWNERS
> SP-1969 - Add Code Owners File #patch

- go.mod
- go.sum
> SP-2038 - Patch x/net vuln #minor

- internal/templatefn/fn.go
- internal/templatefn/fn_test.go
- web/template/mlpa-details.gohtml
> VEGA-2470 Fix date parsing in LPA details template #minor

- web/assets/main.scss
- web/template/search.gohtml
[vega-2443](https://opgtransform.atlassian.net/browse/VEGA-2443)
> vega-2443 Prevent case type cell from wrapping

- internal/server/get_history.go
- internal/server/get_history_test.go
- internal/server/server.go
- internal/sirius/get_events.go
- internal/sirius/get_events_test.go
- web/template/layout/mlpa-header.gohtml
- web/template/mlpa-history.gohtml
> VEGA-2029 create history tab

- docker/sirius-lpa-frontend/Dockerfile
> SP-2083  - patch golang #patch

- internal/sirius/cache.go
> VEGA-2409 Lock/unlock cache map to prevent concurrent write errors #minor

- main.go
> API for slog has changed, fix our code

- web/template/layout/mlpa-header.gohtml
> VEGA-2442 remove issues tab

- docker/test-runner/Dockerfile
> SP-2102 - Pin Pact Prebuilt to last good version #patch

- renovate.json
> VEGA-2482 change patch minor renovate schedule to monthly #patch

- cypress/e2e/search.cy.js
- web/template/search.gohtml
> VEGA-2441 search form links incorrect for digital lpas

- web/assets/handle-create-document-button.js
- web/template/create_document.gohtml
This means that the button will work if JS is switched off.
> VEGA-2452 Use JS to disable button for creating a document #minor

- docker/sirius-lpa-frontend/Dockerfile
> SP-2135 - Patch busybox #patch

- web/assets/dark.scss
> VEGA-2445 Dark mode fixes for inputs, warning and inset text #minor

- cypress/e2e/application-progress.cy.js
- cypress/e2e/digital-lpa.cy.js
- internal/templatefn/fn.go
- internal/templatefn/fn_test.go
> Vega 2504 cannot start progress indicators

- cypress/e2e/digital-lpa.cy.js
- internal/server/assign_task.go
- internal/server/assign_task_test.go
- web/template/assign_task.gohtml
> VEGA-2509 cancel reassign task form

- cypress/e2e/create-additional-draft.cy.js
- web/template/create_additional_draft.gohtml
> VEGA-2455 Cancel button on additional draft page goes to donor page #minor

- cypress/e2e/digital-lpa.cy.js
- web/template/warning.gohtml
> VEGA-2510 can cancel on create warning form

- renovate.json
> Renovate - remove prPriority outside of package rules

- cypress/e2e/clear-task.cy.js
- cypress/e2e/digital-lpa.cy.js
- internal/server/clear_task.go
- internal/server/clear_task_test.go
- internal/server/server.go
- internal/sirius/clear_task.go
- internal/sirius/clear_task_test.go
- web/template/assign_task.gohtml
- web/template/clear_task.gohtml
- web/template/layout/mlpa-case-summary.gohtml
> Vega 2238 manual closing of tasks

- cypress/e2e/application-progress.cy.js
- internal/server/get_application_progress.go
- internal/server/get_application_progress_test.go
- web/template/layout/mlpa-progress-indicator.gohtml
- web/template/layout/pi-certificate-provider-id.gohtml
- web/template/layout/pi-donor-id.gohtml
> VEGA-2419 Cert provider redirects to paper id service

- internal/server/event.go
- internal/server/event_test.go
- internal/templatefn/fn.go
- web/template/event.gohtml
- web/template/layout/mlpa-header.gohtml
> VEGA-2249 Create event menu item #minor

- renovate.json
> VEGA-2577 increase renovate threshold

- cypress/e2e/application-progress.cy.js
- internal/server/get_application_progress.go
- internal/server/get_application_progress_test.go
- web/template/layout/pi-donor-id.gohtml
Need to look at application details since there isn't anything in the LPA Store.
And rename variable for clarity.
Fixes VEGA-2608 #patch
- N/A
- N/A
- N/A
> Permit donor ID check before submission

- cypress/e2e/digital-lpa.cy.js
- docker/puppeteer/Dockerfile
- internal/sirius/digital_lpa.go
- internal/sirius/digital_lpa_test.go
- web/assets/dark.scss
- web/template/mlpa-details.gohtml
> VEGA-2532 Calculate and display registration due date

- cypress/e2e/digital-lpa.cy.js
- internal/sirius/digital_lpa.go
- package.json
- web/template/mlpa-details.gohtml
[VEGA-2626](https://opgtransform.atlassian.net/browse/VEGA-2626?atlOrigin=eyJpIjoiZDg2ZTk4MzJmNzlmNGM0NGI1ZDI2OGMwNzA0YjZiOTAiLCJwIjoiaiJ9)
[VEGA-2626]: https://opgtransform.atlassian.net/browse/VEGA-2626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2626 Cetificate provider and attorney LPA details signed on dates

- cypress/e2e/anomaly.cy.js
- internal/sirius/anomaly_display.go
- internal/sirius/anomaly_display_test.go
- web/template/mlpa-details.gohtml
> VEGA-2494 frontend anomaly changes for attorney decisions

- cypress/e2e/anomaly.cy.js
- internal/sirius/anomaly_display_test.go
- web/template/mlpa-details.gohtml
> VEGA-2495 when the lpa can be used anomaly

- cypress/e2e/anomaly.cy.js
- internal/sirius/anomaly_display_test.go
- internal/sirius/digital_lpa.go
- internal/templatefn/fn.go
- internal/templatefn/fn_test.go
- web/template/mlpa-details.gohtml
> VEGA-2496 life sustaining treatment anomaly

- internal/server/edit_document.go
Publishing a document involves four API requests. Currently any error from these is treated as a system error and handled like a 500, but a validation error should be handled like a 400 and passed into the template.
To avoid doing this four times, I've moved the API calls into a single serial function. If any error is returned, the outer code checks if it's a validation error and handles it more carefully if so.
#patch
- N/A
- N/A
- N/A
> Handle validation errors from editing documents

- docker-compose.yml
- docker/puppeteer/Dockerfile
- docker/sirius-lpa-frontend/Dockerfile
- docker/test-runner/Dockerfile
- web/assets/auto-resize-text-area.js
- web/assets/insert-selector.js
- Use `--ignore-scripts` when installing node packages
- Chain RUN instructions
- Use ADD for remote files rather than curling
- Simplify some JS code
#patch
> Fix some issues identified by SonarCloud

- web/template/mlpa-documents.gohtml
- web/template/mlpa-payments.gohtml
They got broken during the upgrade to v3 of moj-frontend
#patch
> Fix alignment of header action butons

- cypress/e2e/anomaly.cy.js
- web/template/layout/certificate-provider-details.gohtml
- web/template/mlpa-details.gohtml
Frontend PR for showing CP address anomalies
Fixes VEGA-2493
#patch
> VEGA-2493 detect cp address anomaly

- cypress/e2e/manage-attorneys.cy.js
- internal/server/manage_attorneys.go
- internal/server/manage_attorneys_test.go
- internal/server/server.go
- web/template/layout/mlpa-header.gohtml
- web/template/mlpa-manage-attorneys.gohtml
[VEGA-2710](https://opgtransform.atlassian.net/browse/VEGA-2710) This covers adding a new Manage attorney page.
[VEGA-2710]: https://opgtransform.atlassian.net/browse/VEGA-2710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2710 Add initial manage attorneys form

- cypress/e2e/change-attorney-details.cy.js
- internal/server/change_attorney_details.go
- internal/server/change_attorney_details_test.go
- web/template/change-attorney-details.gohtml
- web/template/layout/date.gohtml
> VEGA-2719 Edit replacement attorney details content changes

- cypress/e2e/change-attorney-details.cy.js
- internal/server/change_attorney_details.go
- internal/server/change_attorney_details_test.go
- internal/server/server.go
- internal/sirius/change_attorney_details.go
- internal/sirius/change_attorney_details_test.go
- web/template/change-attorney-details.gohtml
> VEGA-2744 change attorney details form can post

- cypress/e2e/create-draft.cy.js
- internal/server/create_draft.go
- internal/server/create_draft_test.go
- web/template/create_additional_draft.gohtml
- web/template/create_draft.gohtml
- web/template/layout/create_lpa_success_banner.gohtml
[vega-2841](https://opgtransform.atlassian.net/browse/VEGA-2841) Change the create draft LPA success banner to notification
> vega-2841 - update the create draft LPA success banner to notification

- cypress/e2e/change-draft.cy.js
- internal/server/change_donor_details.go
- internal/server/change_draft.go
- internal/server/change_draft_test.go
- internal/server/server.go
- internal/sirius/change_draft.go
- internal/sirius/change_draft_test.go
- internal/sirius/digital_lpa.go
- web/template/change-draft.gohtml
- web/template/mlpa-details.gohtml
This PR covers the changes for VEGA-2770
Ticket adds a change link to the draft LPA on the LPA details page which links to a change draft form.
> VEGA-2770 edit draft 

- cypress/e2e/change-certificate-provider-details.cy.js
- cypress/mocks/cases.js
- cypress/mocks/digitalLpas.js
- cypress/mocks/wiremock.js
- cypress/support/commands.js
- internal/server/change_certificate_provider_details.go
- internal/server/change_certificate_provider_details_test.go
- internal/sirius/change_certificate_provider_details.go
- internal/sirius/change_certificate_provider_details_test.go
- web/template/change-certificate-provider-details.gohtml
[VEGA-2794](https://opgtransform.atlassian.net/browse/VEGA-2794) Front-end updates to allow changes to the Certificate Provider.
[VEGA-2794]: https://opgtransform.atlassian.net/browse/VEGA-2794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2794 Change certificate provider post form

- cypress/e2e/manage-restrictions.cy.js
- internal/server/manage_restrictions.go
- internal/server/manage_restrictions_test.go
- internal/sirius/severance_status_test.go
- internal/templatefn/fn.go
- internal/templatefn/fn_test.go
- web/template/manage-restrictions.gohtml
Ticket to:
- Allow user to change severance not required 
- Displays previous selection on manage restrictions form.
Fixes VEGA-2894
> Vega 2894 allow user to change not required option

- cypress/e2e/change-certificate-provider-details.cy.js
- cypress/e2e/digital-lpa-application-progress.cy.js
- cypress/mocks/digitalLpas.js
- internal/templatefn/fn.go
[VEGA-2477](https://opgtransform.atlassian.net/browse/VEGA-2477) Add progress indicator for the restrictions and conditions.
[VEGA-2477]: https://opgtransform.atlassian.net/browse/VEGA-2477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2477 Application progress indicator for restrictions and conditions

- internal/server/change_certificate_provider_details.go
- internal/server/change_certificate_provider_details_test.go
This PR fixes [VEGA-2906](https://opgtransform.atlassian.net/browse/VEGA-2906)
[VEGA-2906]: https://opgtransform.atlassian.net/browse/VEGA-2906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2906 : Fix to the update of certificate provider details #patch

- cypress/e2e/add-objections.cy.js
- cypress/e2e/add-payment.cy.js
- cypress/e2e/anomaly.cy.js
- cypress/e2e/application-progress.cy.js
- cypress/e2e/apply-fee-reduction.cy.js
- cypress/e2e/change-attorney-details.cy.js
- cypress/e2e/change-case-status.cy.js
- cypress/e2e/change-certificate-provider-details.cy.js
- cypress/e2e/change-donor-details.cy.js
- cypress/e2e/change-draft.cy.js
- cypress/e2e/create-document-digital-lpa.cy.js
- cypress/e2e/digital-lpa-application-progress.cy.js
- cypress/e2e/digital-lpa.cy.js
- cypress/e2e/manage-attorneys.cy.js
- cypress/e2e/manage-restrictions.cy.js
- cypress/e2e/remove-an-attorney.cy.js
- cypress/mocks/digitalLpas.js
- internal/server/add_objection.go
- internal/server/add_objection_test.go
- internal/server/server.go
- internal/sirius/add_objections.go
- internal/sirius/add_objections_test.go
- internal/sirius/case_summary.go
- internal/sirius/case_summary_test.go
- internal/sirius/objections.go
- internal/sirius/objections_test.go
- web/template/add-objection.gohtml
- web/template/layout/mlpa-case-summary.gohtml
- web/template/layout/mlpa-header.gohtml
Ticket to add the objection form, which creates an objection on multiple cases if their status is either: Draft, In Progress or Statutory waiting period.
Fixes VEGA-2649
> VEGA-2649 add objection to lpa case

- internal/sirius/objections_test.go
> VEGA-2651 Temporarily comment out pact test

- internal/sirius/objections_test.go
> VEGA-2958 Comment out GET objections pact test temporarily

- cypress/e2e/manage-restrictions.cy.js
- internal/server/get_lpa_details.go
- internal/server/manage_restrictions.go
- internal/server/manage_restrictions_test.go
- internal/server/server.go
- internal/sirius/edit_severance_application.go
- internal/templatefn/fn.go
- internal/templatefn/fn_test.go
- web/template/confirm-restrictions.gohtml
- web/template/layout/input-date.gohtml
- web/template/layout/restrictions-and-conditions.gohtml
- web/template/manage-restrictions.gohtml
This PR covers [VEGA-2663](https://opgtransform.atlassian.net/browse/VEGA-2663) & [VEGA-2976](https://opgtransform.atlassian.net/browse/VEGA-2976)
[VEGA-2663]: https://opgtransform.atlassian.net/browse/VEGA-2663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VEGA-2976]: https://opgtransform.atlassian.net/browse/VEGA-2976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2663 : Edit Restrictions #minor

- cypress/e2e/attorney-decisions.cy.js
- cypress/e2e/remove-an-attorney.cy.js
- internal/server/manage_attorney_decisions.go
- internal/server/manage_attorney_decisions_test.go
- internal/server/remove_an_attorney.go
- internal/server/remove_an_attorney_test.go
- internal/server/server.go
- web/template/mlpa-attorney-decisions.gohtml
- web/template/mlpa-confirm-attorney-decisions.gohtml
- web/template/mlpa-confirm-attorney-removal.gohtml
- web/template/mlpa-remove-attorney.gohtml
PR to add manage decisions form to the remove attorneys journey when attorney decisions are set to jointly-for-some-severally-for-others.
> Vega 3073 manage decisions when removing attorneys

- cypress/e2e/anomaly.cy.js
- web/template/layout/decision-details.gohtml
> Fix small apostrophe typo

- internal/sirius/ref_data_test.go
> Fix pact errors

- web/template/link_person.gohtml
fixes: [VEGA-3179](https://opgtransform.atlassian.net/browse/VEGA-3179)
[VEGA-3179]: https://opgtransform.atlassian.net/browse/VEGA-3179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-3179 : prevent multiple clicks on link-records button

- cypress/e2e/anomaly.cy.js
- web/assets/main.scss
- web/template/layout/attorney-details.gohtml
- web/template/layout/certificate-provider-details.gohtml
- web/template/layout/decision-details.gohtml
- web/template/layout/information-warning.gohtml
- web/template/layout/replacement-attorney-details.gohtml
> VEGA-2673 changing the red link to blue

- cypress/e2e/anomaly.cy.js
- internal/sirius/anomaly_display.go
- internal/sirius/anomaly_display_test.go
- internal/sirius/deleted_cases_test.go
- internal/templatefn/fn_test.go
- web/template/layout/attorney-details.gohtml
- web/template/layout/certificate-provider-details.gohtml
- web/template/layout/donor-details.gohtml
> VEGA-3184 adding in anomaly for country missing on a signed lpa

- cypress/e2e/digital-lpa.cy.js
- cypress/mocks/migrated-from-pact.json
- internal/server/get_payments.go
- internal/server/get_payments_test.go
- internal/sirius/case.go
- internal/sirius/edit_case_test.go
- internal/sirius/payment_test.go
[VEGA-3092](https://opgtransform.atlassian.net/browse/VEGA-3092) Get expected payment total from Cases API and remove hard-coded fee values.
[VEGA-3092]: https://opgtransform.atlassian.net/browse/VEGA-3092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-3092 Update hard coded fee values

- web/template/edit_dates.gohtml
validation on reciept date to ensure it is not set to a future date.
fixes: [ID-3208](https://opgtransform.atlassian.net/browse/VEGA-3208)
> VEGA-3208 : set max reciept date to today

- internal/sirius/get_events_test.go
> VEGA-3330 fixing failing test
