web/assets/main.js
web/assets/main.scss
web/template/layout/header.gohtml
web/template/layout/page.gohtml
web/template/warning.gohtml

Cypress runs tests in an iframe so `window.top` won't be the one we want to talk to

VEGA-1208 Use window.parent to escape iframe so cypress works

---

cypress/integration/create-event.spec.js
docker/docker-compose.yml
go.mod
go.sum
internal/server/event.go
internal/server/event_test.go
internal/server/server.go
internal/sirius/case.go
internal/sirius/case_test.go
internal/sirius/client.go
internal/sirius/client_test.go
internal/sirius/create_note.go
internal/sirius/create_note_test.go
internal/sirius/note_types.go
internal/sirius/note_types_test.go
internal/sirius/person.go
internal/sirius/person_test.go
internal/sirius/warning_types_test.go
web/template/event.gohtml

Because we switch between using the words "event" and "note" I've tried to stick to using "note" in `internal/sirius`, because that matches the API, and "event" everywhere else.

VEGA-1245 Add form to create an event

---

go.mod
go.sum
main.go
web/assets/main.js
web/assets/main.scss
web/template/layout/page.gohtml

Reduces the base font size by the same factor as Sirius themes so that the text embedded forms isn't larger than the rest of the page.
This has to be applied to the `<html>` element so that it's properly cascaded to all other elements.
Also introduces a proper cache-busting query string based on the sha sum of the contents of `./web/static`
Fixes VEGA-1278 and VEGA-1276 #minor

Reduce font size for embedded forms

---

.github/workflows/sonarqube.yml

As an external collaborator, dependabot doesn't have access to the necessary secrets to run SonarQube

Don't run SonarQube for dependabot PRs #patch

---

package.json
web/assets/dark.scss
web/assets/load-classes.js
web/assets/main.js
web/assets/main.scss
web/template/layout/page.gohtml

Adds support for a dark mode, which is applied if the `siriusTheme` cookie is set to "dark" or "accessible-dark"
I've created a new `load-classes` JavaScript file which adds the following classes:
- `js-enabled`: Always
- `app-!-html-class--embedded` and `app-!-embedded`: If the page is loaded in a frame
- `app-!-html-class--dark`: If the `siriusTheme` cookie is set as above
It blocks the rest of the page loading to ensure the styles are applied ASAP, rather than showing a flash of mis-styled content
VEGA-1282 #major

Add dark mode design

---

internal/sirius/create_donor_test.go
internal/sirius/edit_donor_test.go
internal/sirius/person.go

Otherwise setting a value to `false` will mean it is omitted from the body and won't be changed.
For VEGA-1244 #minoe

Encode empty boolean values to JSON

---

internal/server/add_payment.go
internal/server/edit_payment.go
main.go
web/assets/dark.scss
web/assets/main.scss
web/template/add_payment.gohtml
web/template/edit_payment.gohtml
web/template/payments.gohtml

Content and styling tweaks
Previously missed the fact that if you enter amount in an incorrect format and enter nothing for either source or payment date, a validation error message is shown for the amount however the source and payment date do not show any validation error messages because they were only being validated when we send the request to the API. Added in logic to correct this
VEGA-1467 #patch

Vega 1467 fee widget tweaks

---

internal/server/server.go
internal/sirius/client.go
web/template/error.gohtml

If an API response has a Correlation-Id header, include it in the error response page.
Fixes VEGA-1473 #minor

Include Correlation ID in error pages, if set

---

cypress/e2e/edit-payment.cy.js
internal/server/edit_payment.go
internal/server/edit_payment_test.go
internal/sirius/payment.go
internal/sirius/payment_test.go

Case id is now returned along with the payment information when retrieving a payment by id. This is to prevent users from potentially being able to amend the url param to return payment data for a different case and display unrelated case data for the payment.
#minor

VEGA-1453 Retrieve case data from the payment api endpoint

---

internal/server/edit_payment_test.go

It now includes the case ID, which is necessary to get the case details.
#patch

Fix response of edit payment test

---

cypress/e2e/edit-payment.cy.js
internal/server/edit_payment.go
internal/server/edit_payment_test.go
internal/sirius/payment.go
web/template/payments.gohtml

Enabled cheque payments to be editable by using the Locked field on payments.
Small refactoring tweaks to edit payment url param and test fixes
VEGA-1448 #minor

VEGA-1448 Allow payments by cheque

---

internal/sirius/payment_test.go

In order for [VEGA-1456](https://github.com/ministryofjustice/opg-sirius/pull/7751) sirius side pact test changes to pass and further [VEGA-1456](https://github.com/ministryofjustice/opg-sirius-lpa-frontend/pull/141) lpa-frontend changes to be merged, references to the the case number `9` in `TestPayment` need to be replaced with `800` as the pact test to return a case by case number expects `800`
#minor

Amend case number to facilitate VEGA-1465 pact changes

---

internal/sirius/cache.go
internal/sirius/cache_test.go
internal/sirius/ref_data.go

To reduce the number of calls we make to `/ref-data/*` endpoints, cache the responses for an hour.
The cache will also be reset when the service is redeployed.
For VEGA-1178 #patch

Cache refdata responses

---

internal/sirius/task.go
internal/sirius/task_test.go

It's unusual, but a task can exist without a case. In that situation, the task summary needs to generate without referencing the case.
Fixes VEGA-1507 #patch

Handle task summary if it has no case

---

cypress/e2e/mi-reporting.cy.js
web/assets/loading-button.js
web/assets/main.js
web/template/mi_reporting.gohtml

Because they're not given immediate feedback, we believe some users are clicking on the "Download" button multiple times and re-running the report.
This change disables the button after the first time it's pressed, and adds a notification banner to explain that it will open in a new window when ready.
Fixes VEGA-1506 #minor

Prevent users from rerunning report

---

internal/server/add_complaint_test.go
internal/server/add_payment_test.go
internal/server/allocate_cases_test.go
internal/server/apply_fee_reduction_test.go
internal/server/assign_task_test.go
internal/server/change_status_test.go
internal/server/create_donor_test.go
internal/server/create_investigation_test.go
internal/server/delete_payment_test.go
internal/server/delete_relationship_test.go
internal/server/edit_complaint_test.go
internal/server/edit_dates_test.go
internal/server/edit_donor_test.go
internal/server/edit_fee_reduction_test.go
internal/server/edit_payment_test.go
internal/server/event_test.go
internal/server/get_payments_test.go
internal/server/link_person_test.go
internal/server/mi_reporting_test.go
internal/server/place_investigation_on_hold_test.go
internal/server/relationship_test.go
internal/server/search_donors_test.go
internal/server/search_users_test.go
internal/server/server_test.go
internal/server/task_test.go
internal/server/unlink_person_test.go

This is a little thing we started doing in the modernising repo and makes tests slightly less annoying

Use single definition of expectedError in tests

---

web/assets/dark.scss
web/assets/load-classes.js
web/assets/main.scss
web/template/layout/deleted_cases.gohtml
web/template/search.gohtml

This is required as the new search results page is not embedded, and instead redirects the user to the lpa frontend url. I have applied styling to achieve desired dark mode appearance on search results page

VEGA-1613 enable dark mode on non-embedded pages

---

internal/server/server.go
internal/server/server_test.go
internal/sirius/search.go
internal/sirius/search_donors_test.go
internal/sirius/search_users.go
internal/sirius/search_users_test.go
web/assets/dark.scss
web/assets/select.js

Two main changes here:
- Respond to bad search requests with a ValidationError, not a plain text error
- If the request accepts JSON, return a RFC7807 error page rather than an HTML page
I also added coverage for fieldset labels in dark mode
#patch

Respond appropriately to bad search requests

---

internal/server/server.go
internal/server/server_test.go

Changed error code to 499 for cancelled requests (commonly caused autocomplete search input fields), so that we can distinguish these separately from true 500 errors

VEGA-1576-cancelled-requests-bug

---

internal/sirius/create_contact_test.go
internal/sirius/create_donor_test.go
internal/sirius/edit_donor_test.go
internal/sirius/person.go

Removed `omitempty` tag from `person.go` attributes, otherwise you cannot set values to empty. Included missing data in tests
VEGA-1647

VEGA-1647-removing-details-from-edit-donor-bug

---

cypress/e2e/create-document.cy.js
internal/server/create_document.go
internal/server/create_document_test.go
internal/server/edit_document.go
internal/server/edit_document_test.go
internal/templatefn/fn.go
web/assets/auto-click.js
web/assets/handle-create-document-button.js
web/assets/handle-insert-checkboxes.js
web/assets/main.js
web/assets/main.scss
web/assets/select-tab.js
web/assets/text-editor.js
web/assets/wysiwyg.scss
web/template/create_document.gohtml
web/template/edit_document.gohtml

Fixes to issues discovered when manually testing create/edit document forms
Now
- disables create draft document button when no recipients are selected (instead of a validation error message)
- reloads timeline when a document published 
- adds text-editor content styling
- fixes header and layout issues (e.g. uses full width of widget as the document widget is wider than other widgets)
- fixes new line appearing in text editor due to new line between doctype and html tags

VEGA-1239 document form fixes

---

internal/server/create_document.go

Fixes alphabetical display of document templates

VEGA-1239 display documents in alphabetical order

---

.github/workflows/build.yml

Without being enabled, every version is treated as a real bump.

Use prerelease mode for tags

---

internal/server/create_document.go
internal/server/create_document_test.go
internal/sirius/case.go

To match behaviour of the old form, ensure that correspondents can also be selected when they exist.
Fixes VEGA-1239 #minor

Add correspondent to Create Draft recipients

---

internal/server/create_document.go
web/assets/main.scss
web/template/create_document.gohtml
web/template/edit_document.gohtml
web/template/payments.gohtml

Use smaller checkboxes, make inserts panel/table compact, remove a few spacing classes.
When embedded at tablet width (or wider), use mobile-scale gutters for main page containers.
Fixes VEGA-1711 #minor

Reduce spacing in create document form

---

web/template/layout/error-summary.gohtml

Removes payload failed validation message that appears on validation messages as it is not necessary for users

VEGA-1669 remove unrequired payload failed validation message

---

web/template/edit_document.gohtml

The template code being split onto multiple lines was causing an extra space to be added to the end of the button text eg "Publish draft " which is causing the smoke tests to fail

VEGA fix smoke test issue

---

internal/server/create_document.go
internal/sirius/document_templates.go
internal/sirius/document_templates_test.go

Use the new `order` property to sort inserts, and do this when retrieving from the DB to reduce complexity of server code.
Fixes VEGA-1716 #patch

Sort inserts by sent order

---

web/template/create_document.gohtml
web/template/edit_document.gohtml
web/template/layout/case-details.gohtml
web/template/payments.gohtml

- Move case details to site alongside back button (and remove bold text)
- Make the insert skip button primary
- Move the draft save buttons inline
I also fixed an issue where "HW" LPAs weren't getting the subtype shown in the case details.
Fixes VEGA-1724 #patch

Some create document design changes

---

cypress/e2e/create-document.cy.js
internal/server/create_document.go
internal/server/create_document_test.go
internal/sirius/document.go
internal/sirius/document_test.go
web/assets/handle-insert-checkboxes.js
web/assets/insert-selector.js
web/assets/lib/createElement.js
web/assets/main.js
web/assets/select.js
web/template/create_document.gohtml

Adds a component to the template selection screen which shows the available inserts when you select a document. It has the same design and functionality of the existing insert screen but is inline.
I had to create a new data object in a structure that's useful for JavaScript. The component then generates the DOM either from templates or from directly creating each element (using a helper function called createElement).
The component contains a hidden input called `hasViewedInserts` which causes the next page to be skipped. But if the component fails to load then the input isn't added and the user is taken to the fallback page.
This also ensures the documents are sorted by newest-first on the edit screen, to ensure the newly-created document is always shown first.
Fixes VEGA-1751, …

Show inserts when selecting document template

---

internal/server/create_document.go
internal/server/create_document_test.go
internal/sirius/case.go
internal/sirius/case_test.go
internal/sirius/person.go
internal/sirius/person_test.go
web/template/create_document.gohtml

recipients now follow order in ticket. I have also refactored the create document code to remove unnecessary API calls to get each recipient, as they have already been fetched with the case data.
VEGA-1717 #patch

VEGA-1717 order recipients in create document

---

internal/sirius/case_type.go

Case type is stored in different formats in the DB, including uppercase, lowercase and title case (first letter uppercase). We had not accounted for title case in the case type parser function which was preventing users from creating documents on cases of this type. 
To fix I have converted the input of the case type parser to lowercase to remove case sensitive matching

VEGA - case type parser bug

---

renovate.json

Turn off lockfile maintenance in Renovate: it only updates transient dependencies, which creates lots of noise and doesn't provide us with any benefit

Disable lockfile maintenance

---

.github/workflows/build.yml

It's no longer needed since Renovate can publish and verify any changed Pacts. In its current state, it stops us making any changes to the API contract.
* N/A
* N/A
* N/A
#patch

Remove Compare Pacts step from pipeline

---

web/assets/dark.scss
web/assets/wysiwyg.scss

Reuse the colour we use for links, since raw `govuk-colour("light-blue")` is too dark (not AA compliant).
* N/A
Fixes VEGA-1794 #patch

Lighten document user instructions in dark mode

---

internal/sirius/case.go

we now check that the donor isn't nil before trying to check the donor parent which is causing the nil pointer error on live. VEGA-BUG-FIX #patch

VEGA donor parent child bug fix

---

cypress/e2e/search.cy.js
web/assets/auto-apply-filter.js
web/assets/main.js
web/template/layout/search_filter.gohtml

[VEGA-1723](https://opgtransform.atlassian.net/browse/VEGA-1723) - apply search filters without needing a manual click to reapply. 
Note re accessibility - The auto-applying search filters is a compromise on accessibility because the user would not expect a page refresh, to counter this we could have a partial page reload (the filtered results) that has aria live region, which informs the user that a portion of the page has updated, so the screen reader doesn't read out everything again (article below).
Ref: https://technology.blog.gov.uk/2014/08/14/improving-accessibility-on-gov-uk-search/
[VEGA-1723]: https://opgtransform.atlassian.net/browse/VEGA-1723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[VEGA-1723] Apply search filters automatically

---

renovate.json

[branchNameStrict](https://docs.renovatebot.com/configuration-options/#branchnamestrict) should prevent renovate from creating any branches with `.` in them, which seems to be confusing github-tag-action
#patch

Enable branchNameStrict in Renovate

---

cypress/e2e/create-warning.cy.js
cypress/mocks/migrated-from-pact.json
internal/server/warning.go
internal/server/warning_test.go
internal/sirius/cases_by_donor.go
internal/sirius/cases_by_donor_test.go
web/template/warning.gohtml

The `/donors/:id` doesn't contain any child donor cases, making it impossible to create warnings for them.
`/persons/:id/cases` contains all of the parent and children's cases.
Fixes VEGA-1926 #patch

Load a donor's cases from a specific endpoint

---

cypress/e2e/create-document.cy.js
cypress/mocks/common.json
cypress/mocks/migrated-from-pact.json
internal/server/create_document.go
internal/server/create_document_test.go
internal/sirius/document_templates.go
internal/sirius/document_templates_test.go
internal/sirius/ref_data_test.go
web/assets/insert-selector.js
web/template/create_document.gohtml

Rather than using the template ID refdata.
In doing so we also remove the call to RefDataByCategory. We can also remove `DocumentTemplateRefData` because it's no longer used, and merge `DocumentTemplateTypes` into `DocumentTemplates` because it's just a sorted version of that.
We can also remove the `onScreenSummary` property, including taking it out of the API contract.
#patch

Use API's label property for documents and inserts

---

cypress/e2e/digital-lpa.cy.js
go.mod
go.sum
internal/server/lpa.go
internal/server/lpa_test.go
internal/server/mock_server.go
internal/server/server.go
web/template/create-draft.gohtml

Our existing routes all still work with Chi.
Routes that use `chi.URLParam` need to have been served by Chi, so we must update the test harness to create a mux and then serve the request through it.
Fixes VEGA-1984 #minor

Add Chi router

---

cypress/e2e/payments.cy.js
internal/server/add_payment.go
internal/server/add_payment_test.go
internal/server/apply_fee_reduction.go
internal/server/apply_fee_reduction_test.go
internal/server/delete_payment.go
internal/server/delete_payment_test.go
internal/server/edit_fee_reduction.go
internal/server/edit_fee_reduction_test.go
internal/server/edit_payment.go
internal/server/edit_payment_test.go
internal/server/get_payments.go
internal/server/server.go
web/template/add_payment.gohtml
web/template/apply_fee_reduction.gohtml
web/template/delete_fee_reduction.gohtml
web/template/delete_payment.gohtml
web/template/edit_fee_reduction.gohtml
web/template/edit_payment.gohtml

Created new payments route which uses chi URL param. The route goes to the same page and behaves the same as the existing `/payments?id={id}` route. 
VEGA-1961 #patch
~~- [ ] I have updated the end-to-end tests to work with my changes~~
~~- [ ] I have added styling for Dark Mode~~
~~- [ ] I have checked that my UI changes meet accessibility standards~~

VEGA-1961 use Chi URL param on payments route

---

internal/server/flash.go
internal/server/flash_test.go

Without the Path property, the flash message cookie is not correctly matched when attempting to remove it. This results in the flash message persisting across requests and appearing incorrectly on different cases etc.
It looks like this can't be tested against the app running locally in standalone mode, as the paths appear to be set correctly and the flash cookie *is* deleted as expected.

VEGA-2010 Scope flash cookie to / path #minor

---

cypress/e2e/create-document-digital-lpa.cy.js
internal/server/create_document_digital_lpa.go
internal/server/create_document_digital_lpa_test.go
internal/server/create_draft.go
internal/server/edit_document.go
internal/server/edit_document_test.go
internal/server/flash.go
internal/server/get_documents.go
internal/server/server.go
internal/sirius/case_type.go
internal/sirius/document.go
internal/sirius/document_templates.go
internal/sirius/document_test.go
internal/templatefn/fn.go
web/assets/handle-create-document-button.js
web/assets/insert-selector.js
web/template/edit_document.gohtml
web/template/mlpa-create_document.gohtml
web/template/mlpa-documents.gohtml

Create a new route for creating the document, selecting templates, inserts and recipients. Since the donor record isn't (yet) populated, create a non-case contact to send to.
Tweak the insert-selector JS component so it can handle existing values.
Adapt the edit document form so it can support Digital LPA documents, and show their header.
Show flash messages on the Digital LPA document tab, and generate them when documents are previewed or published.
#minor
- N/A

Create a document for Digital LPAs

---

cypress/mocks/common.json
internal/server/edit_document.go
internal/server/edit_document_test.go
internal/server/get_documents.go
internal/server/get_documents_test.go
internal/sirius/document.go
internal/sirius/document_test.go
web/template/mlpa-documents.gohtml

- Include incoming correspondence when requesting list of documents. This is done by excluding drafts and previews.
- Alter what is shown in the documents table based on document direction (e.g. showing "System Type" for outgoing docs and "type"/"subtype" for incoming)
- Add a download link to each document (previously was `#`)
- N/A
- N/A
For VEGA-2058 #minor

Show incoming correspondence on Digital LPAs

---

internal/sirius/document_test.go

Pact Ruby summarily cannot handle query strings
VEGA-2058 #patch

Attempt to fix Pact failure

---

internal/server/lpa.go
internal/sirius/digital_lpa.go
internal/templatefn/fn.go
web/assets/dark.scss
web/template/layout/mlpa-header.gohtml
web/template/lpa.gohtml

added linked cases tabs to digital lpa case page. The cases are sorted so that their order remains the same when switching between case tabs. 
VEGA-2007 #patch

VEGA-2007 display linked digital lpas

---

go.mod
go.sum
internal/server/create_document.go
internal/server/create_document_digital_lpa.go

We used the experimental package for the `slices.Contains()` method. That was added to the standard library in go 1.21, so we can now import `slices` instead and remove the experimental dependency.
#patch

Replace experimental slices package with `slices`

---

renovate.json

Renovate requires the "minutes" value of a cron schedule to be `*` (since it can't guarantee minute-precision). But that's confusing because it looks like it will run every minute.
Instead, use [later syntax](https://breejs.github.io/later/) which Renovate also supports and which is a little clearer.

Fix renovate schedule

---

web/assets/text-editor.js

Rather than having frame-specific logic, we can just use the data-prefix value to specify the base URL (for themes and plugins) and content CSS (for our custom inside-the-editor CSS).
Fixes VEGA-2288 #patch

Simplify specifying where TinyMCE resources are

---

web/template/edit_complaint.gohtml

We should not set `data-aria-controls` if there's no element with that ID, otherwise govuk-frontend crashes.
Fixes VEGA-2307, introduced by VEGA-2202 #patch

Fix complaint resolution conditional reveals

---

internal/server/delete_relationship.go
internal/server/delete_relationship_test.go
web/template/delete_relationship.gohtml

Error message now appears on form asking user to select a relationship to delete whenever the delete button is pressed without selecting a radio option.

Vega-2312 handle error gracefully #patch

---

web/template/create_draft.gohtml
web/template/mlpa-details.gohtml

Move aria-describedby properties to the input tag
[VEGA-2359](https://opgtransform.atlassian.net/browse/VEGA-2359)
[VEGA-2359]: https://opgtransform.atlassian.net/browse/VEGA-2359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEGA-2359 - Move aria-describedby to <input> tags 

---

internal/server/assign_task.go

We pick an LPA to go back to if the "Cancel" button is pressed. Currently this assumes that every task has a case, but some don't.
Instead, only set the back UID if the task has an LPA.
Fixes VEGA-2576 #patch

Don't try to read UID of null LPA

---

cypress/e2e/digital-lpa.cy.js
web/template/mlpa-details.gohtml

If the LPA's status is "Draft" but there's data in the store, show the data in the store.
NB: we have to check the zero-value of the channel (which is a required field) because the LpaStoreData object doesn't have a nil struct (that's not how Go structs work).
This is initiated by making testing easier, but is also part of a move towards not relying on Sirius to determine a case's status.
Also, fix the whitespace around `newlines-as-br` things: excess whitespace (newlines/indent) was being rendered inappropriately, replace it with a `<p>`.
Fixes VEGA-2578 #minor

Show LPA details if in store

---

internal/server/server_test.go
internal/sirius/client.go
internal/sirius/client_test.go

If a ValidationError has a Detail provided, use that as the error summary.
This allows the error summary to be shown properly in the Sirius UI, rather than the generic "validation error" text.
Discovered in VEGA-2573 #minor
| Before | After |
| ---- | ---- |
| <img width="484" alt="imagen" src="https://github.com/user-attachments/assets/7c69d4a6-f610-4929-8fe5-2abf00e21c32"> |  <img width="489" alt="imagen" src="https://github.com/user-attachments/assets/90195980-698a-4f71-b264-e0f2dcff9315"> |

Show ValidationError details where set

---

cypress/e2e/change-case-status.cy.js
cypress/e2e/digital-lpa.cy.js
cypress/mocks/migrated-from-pact.json
internal/server/change_case_status.go
internal/server/change_case_status_test.go
internal/server/server.go
internal/sirius/digital_lpa.go
internal/sirius/edit_digital_lpa.go
internal/sirius/edit_digital_lpa_status.go
internal/sirius/edit_digital_lpa_status_test.go
internal/templatefn/fn.go
web/template/change_case_status.gohtml
web/template/layout/mlpa-header.gohtml
web/template/layout/radios.gohtml

This PR covers [VEGA-2501](https://opgtransform.atlassian.net/browse/VEGA-2501)
It adds a new template to allow the users to manually change the status of a Digital LPA. 
[VEGA-2501]: https://opgtransform.atlassian.net/browse/VEGA-2501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEGA-2501 : Manual Digital LPA Case Status Change #minor

---

internal/sirius/edit_digital_lpa_status_test.go

This PR is a patch for [VEGA-2501](https://opgtransform.atlassian.net/browse/VEGA-2501)
The 'main' branch workflow is failing due to a Pact test verification failure. This change updates the pact test to remove the response header content type definition since the status returned is a 204.
[VEGA-2501]: https://opgtransform.atlassian.net/browse/VEGA-2501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEGA-2501 : Fix for pact test failure with no content returned #patch

---

cypress/e2e/change-case-status.cy.js
internal/server/change_case_status.go
internal/server/change_case_status_test.go
internal/templatefn/fn.go

This PR covers [VEGA-2500](https://opgtransform.atlassian.net/browse/VEGA-2500)
The PR change adds the redirection of the user back to the LPA Details page after a successful update of the Digital LPA status manually.
[VEGA-2500]: https://opgtransform.atlassian.net/browse/VEGA-2500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEGA-2500 : Handle manual change to cancelled status #minor

---

cypress/e2e/change-donor-details.cy.js
cypress/e2e/digital-lpa.cy.js
internal/server/change_donor_details.go
internal/server/change_donor_details_test.go
internal/server/create_additional_draft.go
internal/server/create_additional_draft_test.go
internal/server/server.go
internal/sirius/change_donor_details.go
internal/sirius/change_donor_details_test.go
web/template/change-donor-details.gohtml
web/template/create_additional_draft.gohtml
web/template/layout/date.gohtml
web/template/layout/donor-details.gohtml
web/template/mlpa-details.gohtml

PR that adds a change link on the donor details section, which directs users to the edit donor details form. 
PR also:
- moves the donor details section to it's own template
- creates a reusable date template 
- Fixes the country drop down menu not working in the create additional draft form
Fixes VEGA-2667

VEGA-2667 edit donor detail form

---

.sonarcloud.properties

They're rarely helpful (and sometimes paying down would cause more harm), distracting and confuse things by making builds look like failures.
#patch

Turn off code duplication checks in SonarCloud

---

internal/sirius/digital_lpa_test.go

[VEGA-2624](https://opgtransform.atlassian.net/jira/software/projects/VEGA/boards/170?selectedIssue=VEGA-2624) This PR covers adding a PACT test for the Due Date response when getting Digital LPA data through the API.
[VEGA-2624]: https://opgtransform.atlassian.net/browse/VEGA-2624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEGA-2624 Add digital LPA due date Pact test

---

internal/templatefn/fn.go
internal/templatefn/fn_test.go

[vega-2701](https://opgtransform.atlassian.net/browse/VEGA-2701) - to add in the finalised content for lifeSustainingTreatment options

vega-2701 - Add content for lifeSustainingTreatment options

---

cypress/e2e/application-progress.cy.js
web/template/layout/pi-certificate-provider-id.gohtml

The person type should be "certificateProvider" not "certificate-provider"
Fixes VEGA-2884 #patch
- N/A
- N/A

Fix link to CP ID check

---

internal/server/remove_an_attorney.go
internal/server/remove_an_attorney_test.go
internal/server/server.go
internal/sirius/change_attorney_status.go
internal/sirius/change_attorney_status_test.go

This PR covers [VEGA-2821](https://opgtransform.atlassian.net/browse/VEGA-2821)
Currently, these frontend changes cater to the removal of an attorney. When the enabling of the replacement attorneys functionality is implemented, then the code will need to be updated to accommodate the additional status changes in the request array.
[VEGA-2821]: https://opgtransform.atlassian.net/browse/VEGA-2821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEGA-2821 : Changes for submitting the remove an attorney form

---

internal/sirius/task_types_test.go

Pact doesn't seem happy expecting an empty object, so check that handle is provided even though we don't use it.
#patch

Fix Pact file

---

cypress/e2e/remove-an-attorney.cy.js
internal/server/remove_an_attorney.go
internal/server/remove_an_attorney_test.go
web/template/mlpa-confirm-attorney-removal.gohtml
web/template/mlpa-remove-attorney.gohtml

This PR covers [VEGA-2771](https://opgtransform.atlassian.net/browse/VEGA-2771)
The implementation around the attorney removal (done initially) has been changed to fit in the enabling of the replacement attorneys so that they can be sent as a single data request of attorney statuses to the API. 
[VEGA-2771]: https://opgtransform.atlassian.net/browse/VEGA-2771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEGA-2771 : Updates for enabling replacement attorney while removing an attorney

---

cypress/e2e/digital-lpa.cy.js
internal/server/get_lpa_details.go
internal/server/get_lpa_details_test.go
web/template/layout/removed-attorney-details.gohtml
web/template/mlpa-details.gohtml

This PR covers [VEGA-2886](https://opgtransform.atlassian.net/browse/VEGA-2886)
As discussed with Katie, it has been agreed to retain the same design (fields) for the Removed Attorney section as is for the current Attorneys and Replacement Attorneys to keep the design consistent. The updated design (updated labels) as per the attached screenshots in the ticket would be applied in a separate ticket covering all the attorney sections together.
[VEGA-2886]: https://opgtransform.atlassian.net/browse/VEGA-2886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEGA-2886 : Add Removed Attorneys section #minor

---

cypress/e2e/digital-lpa.cy.js
internal/server/change_attorney_details.go
internal/server/change_certificate_provider_details.go
internal/server/change_donor_details.go
internal/server/change_draft.go
internal/server/manage_restrictions.go
internal/server/update_decisions.go
web/template/layout/attorney-details.gohtml
web/template/layout/certificate-provider-details.gohtml
web/template/layout/donor-details.gohtml
web/template/layout/replacement-attorney-details.gohtml
web/template/mlpa-details.gohtml

[vega-2844](https://opgtransform.atlassian.net/browse/VEGA-2844)
Change wording in LPA details page
‘change’ link -> ‘Update’
success message ‘changes confirmed’ -> ‘update saved’

vega-2844 update wording of edit buttons and success messages for LPA details page 

---

cypress/e2e/manage-restrictions.cy.js
internal/server/manage_restrictions.go
internal/server/manage_restrictions_test.go
internal/sirius/edit_severance_application.go
internal/sirius/edit_severance_application_test.go
web/template/manage-restrictions.gohtml

This PR covers [VEGA-2871](https://opgtransform.atlassian.net/browse/VEGA-2871)
As part of this PR, there has been some refactoring done to merge in the Donor consent changes with the Severance required changes under a single route and template.
[VEGA-2871]: https://opgtransform.atlassian.net/browse/VEGA-2871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEGA-2871 : Logic for capturing the donor consent for severance

---

go.mod
go.sum
internal/server/change_attorney_details.go
internal/server/change_certificate_provider_details.go
internal/server/change_draft.go
internal/server/create_document_digital_lpa.go
internal/server/get_application_progress.go
internal/server/get_documents.go
internal/server/get_history.go
internal/server/get_lpa_details.go
internal/server/get_payments.go
internal/server/manage_attorneys.go
internal/server/manage_restrictions.go
internal/server/mock_server.go
internal/server/remove_an_attorney.go
internal/server/server.go
internal/server/update_decisions.go

Since 1.22, Go's built-in router provides all the functionality we need
Fixes VEGA-2473 #patch

Replace Chi with native Go router

---

web/template/mlpa-history.gohtml

When a note doesn't have a document, `event.entity.document` is empty. But Go can't easily check that.
Move the logic to a separate block so it can be handled more carefully.
#patch

Handle note/document logic separately in timeline

---

cypress/e2e/manage-restrictions.cy.js
internal/server/manage_restrictions.go
internal/server/manage_restrictions_test.go
internal/sirius/create_draft.go
internal/sirius/edit_severance_application.go
internal/sirius/edit_severance_application_test.go
web/template/manage-restrictions.gohtml

This PR covers [VEGA-2873](https://opgtransform.atlassian.net/browse/VEGA-2873)
I have updated the implementation of the severance flow as part of this ticket to allow the SeveranceApplication object and the bool fields `hasDonorConsented` and `severanceOrdered` to be treated as nil in Go when they are returned as empty from the API. 
In my testing I found that they are treated as empty object or false and so I changed the relevant fields in Go to pointers which then allows the object or the bool fields as nil.
[VEGA-2873]: https://opgtransform.atlassian.net/browse/VEGA-2873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEGA-2873 : Record court order dates for severance

---

internal/server/manage_restrictions.go

This PR fixes [VEGA-2985](https://opgtransform.atlassian.net/browse/VEGA-2985)
The bug occurs because the code was trying to clear a task with id as 0. The check prevents the function call.
[VEGA-2985]: https://opgtransform.atlassian.net/browse/VEGA-2985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEGA-2985 : Added a check for task id to not be 0 #patch

---

web/assets/address-finder.js

The attribute value is controlled and trusted, but it should be plain text so don't treat it as HTML.
#patch

Set innerText, not innerHTML

---

internal/server/server.go

This PR covers [VEGA-2983](https://opgtransform.atlassian.net/browse/VEGA-2983) which is part of [VEGA-2982](https://opgtransform.atlassian.net/browse/VEGA-2982)
[VEGA-2983]: https://opgtransform.atlassian.net/browse/VEGA-2983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VEGA-2982]: https://opgtransform.atlassian.net/browse/VEGA-2982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEGA-2983 : Update the CSP header to allow images from AWS S3 #patch

---

internal/server/create_draft_test.go
internal/server/mi_reporting.go
internal/server/mi_reporting_test.go
internal/server/mock_server.go
internal/server/server.go
internal/server/server_test.go
web/template/mi_reporting.gohtml

[VEGA-3001](https://opgtransform.atlassian.net/browse/VEGA-3001) This PR adds XSRF middleware to check post requests have the XSRF token found in the XSRF token. Some of the server tests needed patching with a call to populate the `request.postForm` data as this was happening in the `getContext` `request.FormValue` method call previously. 
[VEGA-3001]: https://opgtransform.atlassian.net/browse/VEGA-3001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEGA-3001 Implement XSRF protection for all post requests

---

web/template/mlpa-details.gohtml

fixes last part of [VEGA-2590](https://opgtransform.atlassian.net/browse/VEGA-2590)
[VEGA-2590]: https://opgtransform.atlassian.net/browse/VEGA-2590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEGA-2590 : dont show correspondent address when there is no correspondent

---

web/template/mlpa-update-decisions.gohtml

This PR covers [VEGA-3167](https://opgtransform.atlassian.net/browse/VEGA-3167) and [VEGA-3168](https://opgtransform.atlassian.net/browse/VEGA-3168).
[VEGA-3167]: https://opgtransform.atlassian.net/browse/VEGA-3167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VEGA-3168]: https://opgtransform.atlassian.net/browse/VEGA-3168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEGA-3167 : Update the criteria for the missing fields to display them correctly #minor
